name: ML CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-train-eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest (unit + acceptance)
        env:
          PYTHONPATH: ${{ github.workspace }}     # <-- add this line
        run: pytest -q

      - name: Upload metrics
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: model-metrics
          path: artifacts/metrics.json

      - name: Add accuracy to job summary
        if: success()
        run: |
          ACC=$(jq '.accuracy' artifacts/metrics.json)
          echo "### Model Metrics" >> $GITHUB_STEP_SUMMARY
          echo "| metric | value |"    >> $GITHUB_STEP_SUMMARY
          echo "| ------ | ----- |"    >> $GITHUB_STEP_SUMMARY
          echo "| accuracy | $ACC |"  >> $GITHUB_STEP_SUMMARY

      # ---- CD step: build & upload artifact only if tests pass ----
#      - name: Package model artifact
#        if: success()
#        run: |
#          tar czf model_artifacts.tar.gz artifacts/
#      - name: Upload artifact
#        if: success()
#        uses: actions/upload-artifact@v4
#        with:
#          name: iris-model
#          path: model_artifacts.tar.gz